# Generated by Django 4.2.4 on 2023-08-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_course_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Categorie'},
        ),
    ]
