# Generated by Django 4.2.3 on 2023-09-03 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_coursecategory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursecategory",
            options={"verbose_name": "Course Category"},
        ),
    ]
