# Generated by Django 4.2.3 on 2023-08-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("photo", models.ImageField(upload_to="trainers/")),
                ("expertise", models.CharField(max_length=100)),
                ("social_media", models.URLField(blank=True)),
            ],
        ),
    ]
